blank_issues_enabled: true
contact_links:
  - name: Zabbix official documentation
    url: https://www.zabbix.com/documentation/current/en/manual
    about: Use official documentation for product behaviour and syntax details.
